
services:
  spotify_api_db:
    image: postgres:15
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U postgres -d spotify_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes: 
      - ./data:/var/lib/postgresql/data

  
  spotify_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    links:
      - spotify_api_db
    depends_on:
      - spotify_api_db